name: CI
on:
  - push

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [8, 10, 12, 14]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn flow:libdefs

      - run: yarn build
      - run: yarn flow:check
      - run: yarn eslint
      - run: yarn test

  publish:
    name: Publish to npmjs
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get install asciidoctor pandoc

      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - run: yarn install

      - run: yarn build

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
